In [2]:
import pandas as pd
import numpy as np

In [3]:
first_data = pd.read_csv('/content/deliveries.csv')
second_data = pd.read_csv('/content/matches.csv')

In [4]:
first_data.head(10)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.1,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.2,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.3,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.4,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.5,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.6,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,1.1,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,1.2,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,1.3,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,1.4,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
second_data.tail()

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
69,2023,Royal Challengers Bangalore,Gujarat Titans,2023/05/21,70,M Chinnaswamy Stadium,Bengaluru,Gujarat Titans,field,Shubman Gill,Nitin Menon,VK Sharma,VM Dhokre,J Srinath,Gujarat Titans,NaN,6.0,Group
70,2023,Chennai Super Kings,Gujarat Titans,2023/05/23,71,MA Chidambaram Stadium,Chennai,Gujarat Titans,field,RD Gaikwad,AK Chaudhary,CB Gaffaney,VK Sharma,M Nayyar,Chennai Super Kings,15.0,NaN,Qualifier
71,2023,Mumbai Indians,Lucknow Super Giants,2023/05/24,72,MA Chidambaram Stadium,Chennai,Mumbai Indians,bat,Akash Madhwal,BNJ Oxenford,VK Sharma,AK Chaudhary,V Narayan Kutty,Mumbai Indians,81.0,NaN,Eliminator
72,2023,Gujarat Titans,Mumbai Indians,2023/05/26,73,Narendra Modi Stadium,Ahmedabad,Mumbai Indians,field,Shubman Gill,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,J Srinath,Gujarat Titans,62.0,NaN,Qualifier
73,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,Final

In [6]:
first_data.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [7]:
second_data.columns

Index(['season', 'team1', 'team2', 'date', 'match_number', 'venue', 'city',
       'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'winner_runs',
       'winner_wickets', 'match_type'],
      dtype='object')

In [8]:
extras_df = first_data.groupby(['match_id','innings', 'batting_team', 'bowling_team']).agg({'ball':'count', 'byes': 'count', 'legbyes':'count', 'wides':'count','noballs':'count'})

In [9]:
extras_df['total_extras'] = extras_df['byes'] + extras_df['legbyes'] + extras_df['noballs'] + extras_df['wides']

In [10]:
first_data['total_run'] = first_data['runs_off_bat'] + first_data['extras']

In [11]:
first_data['match_number'] = first_data['match_id'].rank(method='dense').astype(int)

In [12]:
first_data

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,total_run,match_number
0,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.1,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
1,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.2,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1,1
2,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.3,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
3,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.4,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
4,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",1,0.5,Chennai Super Kings,Gujarat Titans,DP Conway,RD Gaikwad,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17858,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,74
17859,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,74
17860,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,74
17861,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,74
17862,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,74

In [13]:
total_runs = first_data.groupby(['match_id','innings', 'match_number']).sum()['total_run'].add(1).reset_index()

In [14]:
total_runs

     match_id  innings  match_number  total_run
0     1359475        1             1        179
1     1359475        2             1        183
2     1359476        1             2        192
3     1359476        2             2        147
4     1359477        1             3        194
..        ...      ...           ...        ...
142   1370351        2            72        102
143   1370352        1            73        234
144   1370352        2            73        172
145   1370353        1            74        215
146   1370353        2            74        172

[147 rows x 4 columns]

In [15]:
match_df = second_data.merge(total_runs[['match_number','total_run']],left_on='match_number',right_on='match_number')

In [16]:
match_df

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type,total_run
0,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Group,179
1,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Group,183
2,2023,Punjab Kings,Kolkata Knight Riders,2023/04/01,2,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Kolkata Knight Riders,field,Arshdeep Singh,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Group,192
3,2023,Punjab Kings,Kolkata Knight Riders,2023/04/01,2,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Kolkata Knight Riders,field,Arshdeep Singh,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Group,147
4,2023,Lucknow Super Giants,Delhi Capitals,2023/04/01,3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Delhi Capitals,field,MA Wood,AK Chaudhary,NA Patwardhan,M Kuppuraj,DS Manohar,Lucknow Super Giants,50.0,NaN,Group,194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,2023,Mumbai Indians,Lucknow Super Giants,2023/05/24,72,MA Chidambaram Stadium,Chennai,Mumbai Indians,bat,Akash Madhwal,BNJ Oxenford,VK Sharma,AK Chaudhary,V Narayan Kutty,Mumbai Indians,81.0,NaN,Eliminator,102
143,2023,Gujarat Titans,Mumbai Indians,2023/05/26,73,Narendra Modi Stadium,Ahmedabad,Mumbai Indians,field,Shubman Gill,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,J Srinath,Gujarat Titans,62.0,NaN,Qualifier,234
144,2023,Gujarat Titans,Mumbai Indians,2023/05/26,73,Narendra Modi Stadium,Ahmedabad,Mumbai Indians,field,Shubman Gill,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,J Srinath,Gujarat Titans,62.0,NaN,Qualifier,172
145,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,Final,215
146,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,Final,172

In [17]:
team_df = match_df[['match_number','city','winner','total_run', 'team1', 'team2']]

In [18]:
team_df

,match_number,city,winner,total_run,team1,team2
0,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans
1,1,Ahmedabad,Gujarat Titans,183,Chennai Super Kings,Gujarat Titans
2,2,Chandigarh,Punjab Kings,192,Punjab Kings,Kolkata Knight Riders
3,2,Chandigarh,Punjab Kings,147,Punjab Kings,Kolkata Knight Riders
4,3,Lucknow,Lucknow Super Giants,194,Lucknow Super Giants,Delhi Capitals
...,...,...,...,...,...,...
142,72,Chennai,Mumbai Indians,102,Mumbai Indians,Lucknow Super Giants
143,73,Ahmedabad,Gujarat Titans,234,Gujarat Titans,Mumbai Indians
144,73,Ahmedabad,Gujarat Titans,172,Gujarat Titans,Mumbai Indians
145,74,Ahmedabad,Chennai Super Kings,215,Gujarat Titans,Chennai Super Kings
146,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings

In [19]:
second_innings = team_df.merge(first_data,on='match_number')
second_innings

,match_number,city,winner,total_run_x,team1,team2,match_id,season,start_date,venue,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,total_run_y
0,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1
2,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35603,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35604,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35605,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35606,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
35607,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [20]:
second_innings = second_innings[second_innings['innings']==2]
second_innings.shape

(17242, 29)

In [21]:
second_innings['bowling_team'].unique()

array(['Chennai Super Kings', 'Punjab Kings', 'Lucknow Super Giants',
       'Rajasthan Royals', 'Mumbai Indians', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Sunrisers Hyderabad', 'Gujarat Titans',
       'Royal Challengers Bangalore'], dtype=object)

In [22]:
second_innings['current_Score'] = second_innings.groupby('match_id')['total_run_y'].cumsum()
second_innings

<ipython-input-22-5c18e3fb157d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['current_Score'] = second_innings.groupby('match_id')['total_run_y'].cumsum()

,match_number,city,winner,total_run_x,team1,team2,match_id,season,start_date,venue,...,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,total_run_y,current_Score
121,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
122,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
123,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
124,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
125,1,Ahmedabad,Gujarat Titans,179,Chennai Super Kings,Gujarat Titans,1359475,2023,2023-03-31,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35603,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,330
35604,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,331
35605,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,332
35606,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,338
35607,74,Ahmedabad,Chennai Super Kings,172,Gujarat Titans,Chennai Super Kings,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,342

In [23]:
second_inning = second_innings[['match_number', 'city', 'winner', 'team1', 'team2','match_id', 'innings', 'ball', 'player_dismissed', 'batting_team', 'bowling_team', 'runs_off_bat', 'extras', 'total_run_y']]

In [24]:
second_inning

,match_number,city,winner,team1,team2,match_id,innings,ball,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y
121,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.1,NaN,Gujarat Titans,Chennai Super Kings,0,0,0
122,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0
123,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.3,NaN,Gujarat Titans,Chennai Super Kings,0,0,0
124,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.4,NaN,Gujarat Titans,Chennai Super Kings,1,0,1
125,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.5,NaN,Gujarat Titans,Chennai Super Kings,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35603,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1
35604,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.3,NaN,Chennai Super Kings,Gujarat Titans,1,0,1
35605,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.4,NaN,Chennai Super Kings,Gujarat Titans,1,0,1
35606,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.5,NaN,Chennai Super Kings,Gujarat Titans,6,0,6
35607,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.6,NaN,Chennai Super Kings,Gujarat Titans,4,0,4

In [25]:
second_inning = second_inning.drop_duplicates(subset=['match_number', 'city', 'winner', 'team1', 'team2','match_id', 'innings', 'ball', 'player_dismissed','batting_team', 'bowling_team', 'runs_off_bat', 'extras', 'total_run_y'])

In [26]:
second_inning

,match_number,city,winner,team1,team2,match_id,innings,ball,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y
121,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.1,NaN,Gujarat Titans,Chennai Super Kings,0,0,0
122,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0
123,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.3,NaN,Gujarat Titans,Chennai Super Kings,0,0,0
124,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.4,NaN,Gujarat Titans,Chennai Super Kings,1,0,1
125,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.5,NaN,Gujarat Titans,Chennai Super Kings,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35387,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1
35388,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.3,NaN,Chennai Super Kings,Gujarat Titans,1,0,1
35389,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.4,NaN,Chennai Super Kings,Gujarat Titans,1,0,1
35390,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.5,NaN,Chennai Super Kings,Gujarat Titans,6,0,6
35391,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.6,NaN,Chennai Super Kings,Gujarat Titans,4,0,4

In [27]:
second_inning['current_Score'] = second_inning.groupby('match_number')['total_run_y'].cumsum()
second_inning

<ipython-input-27-6c7a2ee743d8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_inning['current_Score'] = second_inning.groupby('match_number')['total_run_y'].cumsum()

,match_number,city,winner,team1,team2,match_id,innings,ball,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y,current_Score
121,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.1,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0
122,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0
123,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.3,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0
124,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.4,NaN,Gujarat Titans,Chennai Super Kings,1,0,1,1
125,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.5,NaN,Gujarat Titans,Chennai Super Kings,2,0,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35387,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,159
35388,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.3,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,160
35389,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.4,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,161
35390,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.5,NaN,Chennai Super Kings,Gujarat Titans,6,0,6,167
35391,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.6,NaN,Chennai Super Kings,Gujarat Titans,4,0,4,171

In [28]:
first_innings = match_df.merge(first_data,on='match_number')
first_innings

,season_x,team1,team2,date,match_number,venue_x,city,toss_winner,toss_decision,player_of_match,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,total_run_y
0,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1
2,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,2023,Chennai Super Kings,Gujarat Titans,2023/03/31,1,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,field,Rashid Khan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35603,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35604,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35605,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35606,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
35607,2023,Gujarat Titans,Chennai Super Kings,2023/05/29,74,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,field,DP Conway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [29]:
first_innings = first_innings[first_innings['innings']==1]
first_innings.shape

(18366, 42)

In [30]:
first_innings = first_innings.drop_duplicates(subset=['match_number', 'city', 'winner', 'team1', 'team2', 'match_id', 'innings', 'ball', 'batting_team', 'bowling_team', 'runs_off_bat', 'extras', 'total_run_y'])

In [31]:
max_total_run_x_per_match = first_innings.groupby('match_number')['total_run_x'].max()

result_list = max_total_run_x_per_match.reset_index().values.tolist()

In [32]:
result_list

[[1, 179],
 [2, 192],
 [3, 194],
 [4, 204],
 [5, 172],
 [6, 218],
 [7, 163],
 [8, 198],
 [9, 205],
 [10, 122],
 [11, 200],
 [12, 158],
 [13, 205],
 [14, 144],
 [15, 213],
 [16, 173],
 [17, 176],
 [18, 154],
 [19, 229],
 [20, 175],
 [21, 160],
 [22, 186],
 [23, 178],
 [24, 227],
 [25, 193],
 [26, 155],
 [27, 175],
 [28, 128],
 [29, 135],
 [30, 136],
 [31, 215],
 [32, 190],
 [33, 236],
 [34, 145],
 [35, 208],
 [36, 201],
 [37, 203],
 [38, 258],
 [39, 180],
 [40, 198],
 [41, 201],
 [42, 213],
 [43, 127],
 [44, 131],
 [45, 126],
 [46, 215],
 [47, 172],
 [48, 119],
 [49, 140],
 [50, 182],
 [51, 228],
 [52, 215],
 [53, 180],
 [54, 200],
 [55, 168],
 [56, 150],
 [57, 219],
 [58, 183],
 [59, 168],
 [60, 172],
 [61, 145],
 [62, 189],
 [63, 178],
 [64, 214],
 [65, 187],
 [66, 188],
 [67, 224],
 [68, 177],
 [69, 201],
 [70, 198],
 [71, 173],
 [72, 183],
 [73, 234],
 [74, 215]]

In [33]:
target_df = pd.DataFrame(result_list, columns=['match_number', 'max_total_run_x'])
second_inning = pd.merge(second_inning, target_df, on='match_number', how='left')

In [34]:
second_inning

,match_number,city,winner,team1,team2,match_id,innings,ball,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y,current_Score,max_total_run_x
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.1,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.3,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.4,NaN,Gujarat Titans,Chennai Super Kings,1,0,1,1,179
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,0.5,NaN,Gujarat Titans,Chennai Super Kings,2,0,2,3,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,159,215
8617,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.3,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,160,215
8618,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.4,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,161,215
8619,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.5,NaN,Chennai Super Kings,Gujarat Titans,6,0,6,167,215
8620,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,14.6,NaN,Chennai Super Kings,Gujarat Titans,4,0,4,171,215

In [35]:
second_inning[['over', 'balls']] = second_inning['ball'].astype(str).str.split('.', expand=True)
second_inning['over'] = second_inning['over'].astype(int)
second_inning['balls'] = second_inning['balls'].astype(int)

In [36]:
second_inning = second_inning.drop(['ball'], axis=1)
second_inning

,match_number,city,winner,team1,team2,match_id,innings,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y,current_Score,max_total_run_x,over,balls
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,1
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,2
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,3
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,1,0,1,1,179,0,4
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,2,0,2,3,179,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,159,215,14,2
8617,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,160,215,14,3
8618,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,161,215,14,4
8619,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,6,0,6,167,215,14,5
8620,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,4,0,4,171,215,14,6

In [37]:
second_inning['current_Score'] = second_inning.groupby('match_number')['total_run_y'].cumsum()
second_inning

,match_number,city,winner,team1,team2,match_id,innings,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y,current_Score,max_total_run_x,over,balls
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,1
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,2
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,3
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,1,0,1,1,179,0,4
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,2,0,2,3,179,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,159,215,14,2
8617,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,160,215,14,3
8618,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,161,215,14,4
8619,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,6,0,6,167,215,14,5
8620,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,4,0,4,171,215,14,6

In [38]:
second_inning['runs_left'] = second_inning['max_total_run_x'] - second_inning['current_Score']
second_inning

,match_number,city,winner,team1,team2,match_id,innings,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y,current_Score,max_total_run_x,over,balls,runs_left
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,1,179
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,2,179
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,3,179
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,1,0,1,1,179,0,4,178
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,2,0,2,3,179,0,5,176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,159,215,14,2,56
8617,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,160,215,14,3,55
8618,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,161,215,14,4,54
8619,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,6,0,6,167,215,14,5,48
8620,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,4,0,4,171,215,14,6,44

In [39]:
second_inning['balls_left'] = 120 - (second_inning['over']*6 +second_inning['balls'])
second_inning

,match_number,city,winner,team1,team2,match_id,innings,player_dismissed,batting_team,bowling_team,runs_off_bat,extras,total_run_y,current_Score,max_total_run_x,over,balls,runs_left,balls_left
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,1,179,119
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,2,179,118
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,0,0,0,0,179,0,3,179,117
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,1,0,1,1,179,0,4,178,116
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,2,0,2,3,179,0,5,176,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,159,215,14,2,56,34
8617,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,160,215,14,3,55,33
8618,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,1,0,1,161,215,14,4,54,32
8619,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,6,0,6,167,215,14,5,48,31
8620,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,4,0,4,171,215,14,6,44,30

In [40]:
columns_to_check = ['current_Score', 'runs_left', 'balls_left']

negative_counts = second_inning[columns_to_check].lt(0).sum()

print("Number of negative values in each column:")
print(negative_counts)

Number of negative values in each column:
current_Score     0
runs_left        17
balls_left       19
dtype: int64

In [41]:
second_inning['crr'] = round((second_inning['current_Score']*6)/(120 - second_inning['balls_left']),2)
second_inning['rrr'] = round((second_inning['runs_left']*6)/(second_inning['balls_left']),2)
second_inning

,match_number,city,winner,team1,team2,match_id,innings,player_dismissed,batting_team,bowling_team,...,extras,total_run_y,current_Score,max_total_run_x,over,balls,runs_left,balls_left,crr,rrr
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,0,0,179,0,1,179,119,0.00,9.03
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,0,0,179,0,2,179,118,0.00,9.10
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,0,0,179,0,3,179,117,0.00,9.18
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,1,1,179,0,4,178,116,1.50,9.21
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,2,3,179,0,5,176,115,3.60,9.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,...,0,1,159,215,14,2,56,34,11.09,9.88
8617,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,...,0,1,160,215,14,3,55,33,11.03,10.00
8618,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,...,0,1,161,215,14,4,54,32,10.98,10.12
8619,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,...,0,6,167,215,14,5,48,31,11.26,9.29
8620,74,Ahmedabad,Chennai Super Kings,Gujarat Titans,Chennai Super Kings,1370353,2,NaN,Chennai Super Kings,Gujarat Titans,...,0,4,171,215,14,6,44,30,11.40,8.80

In [42]:
def winner(team):
    return 1 if team['batting_team'] == team['winner'] else 0

In [43]:
second_inning['results'] = second_inning.apply(winner,axis=1)
second_inning.head()

,match_number,city,winner,team1,team2,match_id,innings,player_dismissed,batting_team,bowling_team,...,total_run_y,current_Score,max_total_run_x,over,balls,runs_left,balls_left,crr,rrr,results
0,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,0,179,0,1,179,119,0.0,9.03,1
1,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,0,179,0,2,179,118,0.0,9.10,1
2,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,0,0,179,0,3,179,117,0.0,9.18,1
3,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,1,1,179,0,4,178,116,1.5,9.21,1
4,1,Ahmedabad,Gujarat Titans,Chennai Super Kings,Gujarat Titans,1359475,2,NaN,Gujarat Titans,Chennai Super Kings,...,2,3,179,0,5,176,115,3.6,9.18,1

In [44]:
required_data = second_inning[['batting_team','bowling_team','city','runs_left','balls_left','max_total_run_x','crr','rrr','results']]
required_data

,batting_team,bowling_team,city,runs_left,balls_left,max_total_run_x,crr,rrr,results
0,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,119,179,0.00,9.03,1
1,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,118,179,0.00,9.10,1
2,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,117,179,0.00,9.18,1
3,Gujarat Titans,Chennai Super Kings,Ahmedabad,178,116,179,1.50,9.21,1
4,Gujarat Titans,Chennai Super Kings,Ahmedabad,176,115,179,3.60,9.18,1
...,...,...,...,...,...,...,...,...,...
8616,Chennai Super Kings,Gujarat Titans,Ahmedabad,56,34,215,11.09,9.88,1
8617,Chennai Super Kings,Gujarat Titans,Ahmedabad,55,33,215,11.03,10.00,1
8618,Chennai Super Kings,Gujarat Titans,Ahmedabad,54,32,215,10.98,10.12,1
8619,Chennai Super Kings,Gujarat Titans,Ahmedabad,48,31,215,11.26,9.29,1
8620,Chennai Super Kings,Gujarat Titans,Ahmedabad,44,30,215,11.40,8.80,1

In [45]:
required_data = required_data.replace([np.inf, -np.inf], np.nan)
required_data = required_data.dropna()

In [46]:
required_data = required_data[required_data['crr'] >= 0]

In [47]:
columns_to_check = ['runs_left', 'balls_left', 'max_total_run_x', 'crr', 'rrr', 'results']

required_data = required_data[~(required_data[columns_to_check] < 0).any(axis=1)]

In [48]:
numeric = required_data[['runs_left', 'balls_left', 'max_total_run_x', 'crr', 'rrr', 'results']]
has_infinite_values = np.any(np.isinf(numeric))

has_negative_values = (numeric < 0).any().any()

has_null_values = numeric.isnull().any().any()

print(f"Has Infinite Values: {has_infinite_values}")
print(f"Has Negative Values: {has_negative_values}")
print(f"Has Null Values: {has_null_values}")

Has Infinite Values: False
Has Negative Values: False
Has Null Values: False

In [49]:
required_data.head(10)

,batting_team,bowling_team,city,runs_left,balls_left,max_total_run_x,crr,rrr,results
0,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,119,179,0.00,9.03,1
1,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,118,179,0.00,9.10,1
2,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,117,179,0.00,9.18,1
3,Gujarat Titans,Chennai Super Kings,Ahmedabad,178,116,179,1.50,9.21,1
4,Gujarat Titans,Chennai Super Kings,Ahmedabad,176,115,179,3.60,9.18,1
5,Gujarat Titans,Chennai Super Kings,Ahmedabad,176,114,179,3.00,9.26,1
6,Gujarat Titans,Chennai Super Kings,Ahmedabad,170,113,179,7.71,9.03,1
7,Gujarat Titans,Chennai Super Kings,Ahmedabad,166,112,179,9.75,8.89,1
8,Gujarat Titans,Chennai Super Kings,Ahmedabad,165,111,179,9.33,8.92,1
9,Gujarat Titans,Chennai Super Kings,Ahmedabad,165,110,179,8.40,9.00,1

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pickle

In [51]:
required_data.to_csv("ipl2023_refined.csv", index=False)

In [52]:
df = pd.read_csv('/content/ipl2023_refined.csv')

In [53]:
df.head()

,batting_team,bowling_team,city,runs_left,balls_left,max_total_run_x,crr,rrr,results
0,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,119,179,0.0,9.03,1
1,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,118,179,0.0,9.10,1
2,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,117,179,0.0,9.18,1
3,Gujarat Titans,Chennai Super Kings,Ahmedabad,178,116,179,1.5,9.21,1
4,Gujarat Titans,Chennai Super Kings,Ahmedabad,176,115,179,3.6,9.18,1

In [54]:
x = df.iloc[:, :-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [55]:
x_train

,batting_team,bowling_team,city,runs_left,balls_left,max_total_run_x,crr,rrr
2317,Delhi Capitals,Royal Challengers Bangalore,Bengaluru,77,36,175,7.00,12.83
8309,Lucknow Super Giants,Mumbai Indians,Chennai,96,52,183,7.68,11.08
756,Gujarat Titans,Delhi Capitals,Delhi,94,69,163,8.12,8.17
8161,Gujarat Titans,Chennai Super Kings,Chennai,118,68,173,6.35,10.41
4331,Chennai Super Kings,Rajasthan Royals,Jaipur,132,62,203,7.34,12.77
...,...,...,...,...,...,...,...,...
5734,Delhi Capitals,Royal Challengers Bangalore,Delhi,84,67,182,11.09,7.52
5191,Gujarat Titans,Delhi Capitals,Ahmedabad,77,54,131,4.91,8.56
5390,Sunrisers Hyderabad,Kolkata Knight Riders,Hyderabad,134,93,172,8.44,8.65
860,Rajasthan Royals,Punjab Kings,Guwahati,137,80,198,9.15,10.28
7270,Punjab Kings,Delhi Capitals,Dharamsala,207,107,214,3.23,11.61

In [56]:
trf = ColumnTransformer([('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])],remainder='passthrough')

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
lr_pipe = Pipeline([('step1',trf),('step2',LogisticRegression(solver='liblinear'))])

In [59]:
from sklearn.pipeline import Pipeline
lr_pipe.fit(x_train,y_train)
y_pred = lr_pipe.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8725146198830409

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [60]:
x_test

,batting_team,bowling_team,city,runs_left,balls_left,max_total_run_x,crr,rrr
1558,Sunrisers Hyderabad,Punjab Kings,Hyderabad,102,73,144,5.36,8.38
8167,Gujarat Titans,Chennai Super Kings,Chennai,104,62,173,7.14,10.06
5551,Gujarat Titans,Rajasthan Royals,Jaipur,31,57,119,8.38,3.26
4626,Gujarat Titans,Kolkata Knight Riders,Kolkata,13,17,180,9.73,4.59
623,Lucknow Super Giants,Chennai Super Kings,Chennai,135,74,218,10.83,10.95
...,...,...,...,...,...,...,...,...
624,Lucknow Super Giants,Chennai Super Kings,Chennai,135,73,218,10.60,11.10
2523,Mumbai Indians,Kolkata Knight Riders,Mumbai,96,72,186,11.25,8.00
5213,Gujarat Titans,Delhi Capitals,Ahmedabad,55,33,131,5.24,10.00
2189,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,106,39,229,9.11,16.31
5807,Lucknow Super Giants,Gujarat Titans,Ahmedabad,183,96,228,11.25,11.44

In [61]:
x_test.iloc[10]

batting_team       Kolkata Knight Riders
bowling_team                Punjab Kings
city                             Kolkata
runs_left                            105
balls_left                            64
max_total_run_x                      180
crr                                 8.04
rrr                                 9.84
Name: 6086, dtype: object

In [62]:
lr_pipe.predict_proba(x_test)[10]

array([0.2114337, 0.7885663])

As per the logistic regression classifier, this shows, 79% chances of KKR winning the game and Punjab have 21% chances to win the game. (given the current run rate and rrr)

Trying through random forest classifier

In [63]:
ra_pipe = Pipeline([('step1',trf),('step2',RandomForestClassifier())])

In [64]:
ra_pipe.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', RandomForestClassifier())])

In [65]:
from sklearn.pipeline import Pipeline
ra_pipe.fit(x_train,y_train)
y_pred = ra_pipe.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

1.0

In [66]:
import pickle
pickle.dump(ra_pipe,open('ra_pipe.pkl','wb'))

In [67]:
x_test.iloc[10]

batting_team       Kolkata Knight Riders
bowling_team                Punjab Kings
city                             Kolkata
runs_left                            105
balls_left                            64
max_total_run_x                      180
crr                                 8.04
rrr                                 9.84
Name: 6086, dtype: object

In [68]:
ra_pipe.predict_proba(x_test)[10]

array([0., 1.])

This shows that the game is in KKR's favor

In [69]:
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score, classification_report

In [70]:
encoded_df = pd.get_dummies(data=df, columns=['batting_team','bowling_team','city'])

In [71]:
encoded_df.to_csv("encoded_ipl_2023.csv", index=False)
from IPython.display import FileLink
FileLink("encoded_ipl_2023.csv")

/content/encoded_ipl_2023.csv

In [72]:
encoded_df.head()

,runs_left,balls_left,max_total_run_x,crr,rrr,results,batting_team_Chennai Super Kings,batting_team_Delhi Capitals,batting_team_Gujarat Titans,batting_team_Kolkata Knight Riders,...,city_Chandigarh,city_Chennai,city_Delhi,city_Dharamsala,city_Guwahati,city_Hyderabad,city_Jaipur,city_Kolkata,city_Lucknow,city_Mumbai
0,179,119,179,0.0,9.03,1,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,179,118,179,0.0,9.10,1,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,179,117,179,0.0,9.18,1,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,178,116,179,1.5,9.21,1,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,176,115,179,3.6,9.18,1,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

In [73]:
encoded_df.columns

Index(['runs_left', 'balls_left', 'max_total_run_x', 'crr', 'rrr', 'results',
       'batting_team_Chennai Super Kings', 'batting_team_Delhi Capitals',
       'batting_team_Gujarat Titans', 'batting_team_Kolkata Knight Riders',
       'batting_team_Lucknow Super Giants', 'batting_team_Mumbai Indians',
       'batting_team_Punjab Kings', 'batting_team_Rajasthan Royals',
       'batting_team_Royal Challengers Bangalore',
       'batting_team_Sunrisers Hyderabad', 'bowling_team_Chennai Super Kings',
       'bowling_team_Delhi Capitals', 'bowling_team_Gujarat Titans',
       'bowling_team_Kolkata Knight Riders',
       'bowling_team_Lucknow Super Giants', 'bowling_team_Mumbai Indians',
       'bowling_team_Punjab Kings', 'bowling_team_Rajasthan Royals',
       'bowling_team_Royal Challengers Bangalore',
       'bowling_team_Sunrisers Hyderabad', 'city_Ahmedabad', 'city_Bengaluru',
       'city_Chandigarh', 'city_Chennai', 'city_Delhi', 'city_Dharamsala',
       'city_Guwahati', 'city_Hyderabad', 'city_Jaipur', 'city_Kolkata',
       'city_Lucknow', 'city_Mumbai'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

X = encoded_df.drop('results', axis=1)
y = encoded_df['results']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    'SVM': SVC(),
    'Logistic Regression': LogisticRegression(),
    'Random Forest': RandomForestClassifier(),
    'KNN': KNeighborsClassifier()
}


for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))

ann_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

ann_model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
ann_model.fit(X_train_scaled, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=0)
ann_pred = (ann_model.predict(X_test_scaled) > 0.5).astype(int)
print("ANN Accuracy:", accuracy_score(y_test, ann_pred))
print(classification_report(y_test, ann_pred))

def get_user_input():
    print("Please enter the following details:")

    batting_team = input("Batting team: ")
    bowling_team = input("Bowling team: ")
    city = input("City: ")
    runs_left = float(input("Runs left: "))
    balls_left = float(input("Balls left: "))
    max_total_run_x = float(input("Maximum total runs: "))
    crr = float(input("Current run rate: "))
    rrr = (runs_left / balls_left) * 6
    print(f"Required run rate: {rrr:.2f}")

    return batting_team, bowling_team, city, runs_left, balls_left, max_total_run_x, crr, rrr

def predict_winner(batting_team, bowling_team, city, runs_left, balls_left, max_total_run_x, crr, rrr):
    input_data = pd.DataFrame({
        'runs_left': [runs_left],
        'balls_left': [balls_left],
        'max_total_run_x': [max_total_run_x],
        'crr': [crr],
        'rrr': [rrr]
    })

    for col in X.columns:
        if col.startswith('batting_team_'):
            input_data[col] = 1 if col == f'batting_team_{batting_team}' else 0
        elif col.startswith('bowling_team_'):
            input_data[col] = 1 if col == f'bowling_team_{bowling_team}' else 0
        elif col.startswith('city_'):
            input_data[col] = 1 if col == f'city_{city}' else 0

    for col in X.columns:
        if col not in input_data.columns:
            input_data[col] = 0

    input_data = input_data[X.columns]

    input_scaled = scaler.transform(input_data)

    predictions = {}
    for name, model in models.items():
        predictions[name] = model.predict(input_scaled)[0]

    predictions['ANN'] = 'Win' if ann_model.predict(input_scaled)[0, 0] > 0.5 else 'Loss'

    return predictions

if __name__ == "__main__":
    while True:
        batting_team, bowling_team, city, runs_left, balls_left, max_total_run_x, crr, rrr = get_user_input()

        prediction = predict_winner(
            batting_team=batting_team,
            bowling_team=bowling_team,
            city=city,
            runs_left=runs_left,
            balls_left=balls_left,
            max_total_run_x=max_total_run_x,
            crr=crr,
            rrr=rrr
        )

        print("\nPredictions:")
        for model, result in prediction.items():
            print(f"{model}: {result}")

        while True:
            another = input("\nDo you want to make another prediction? (yes/no): ").lower()
            if another == 'yes':
                print("Let's make another prediction.")
                break
            elif another == 'no':
                print("Thank you for using the winning prediction system")
                exit()
            else:
                print("Invalid. Please enter 'yes' or 'no'")

SVM Accuracy: 0.9994152046783625
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       933
           1       1.00      1.00      1.00       777

    accuracy                           1.00      1710
   macro avg       1.00      1.00      1.00      1710
weighted avg       1.00      1.00      1.00      1710

Logistic Regression Accuracy: 0.8707602339181286
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       933
           1       0.86      0.85      0.86       777

    accuracy                           0.87      1710
   macro avg       0.87      0.87      0.87      1710
weighted avg       0.87      0.87      0.87      1710

Random Forest Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       933
           1       1.00      1.00      1.00       777

    accuracy                           1.00      1710
   macro avg       1.00      1.00      1.00      1710
weighted avg       1.00      1.00      1.00      1710

KNN Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       933
           1       1.00      1.00      1.00       777

    accuracy                           1.00      1710
   macro avg       1.00      1.00      1.00      1710
weighted avg       1.00      1.00      1.00      1710

54/54 [==============================] - 0s 1ms/step
ANN Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       933
           1       1.00      1.00      1.00       777

    accuracy                           1.00      1710
   macro avg       1.00      1.00      1.00      1710
weighted avg       1.00      1.00      1.00      1710

Please enter the following details:
Batting team: Rajasthan Royals
Bowling team: Sunrisers Hyderabad
City: Chennai
Runs left: 74
Balls left: 30
Maximum total runs: 176
Current run rate: 6.8
Required run rate: 14.80
1/1 [==============================] - 0s 19ms/step

Predictions:
SVM: 1
Logistic Regression: 0
Random Forest: 0
KNN: 0
ANN: Loss

Do you want to make another prediction? (yes/no): yes
Let's make another prediction.
Please enter the following details:
Batting team: Lucknow Super Giants
Bowling team: Mumbai Indians
City: Lucknow
Runs left: 22
Balls left: 18
Maximum total runs: 145
Current run rate: 7.33
Required run rate: 7.33
1/1 [==============================] - 0s 21ms/step

Predictions:
SVM: 1
Logistic Regression: 1
Random Forest: 1
KNN: 0
ANN: Loss

Do you want to make another prediction? (yes/no): no
Thank you for using the winning prediction system